'use client';

import Navbar from '@/components/ui/Navbar';
import Footer from '@/components/ui/Footer';
import { Bot, Globe, BarChart3, MessageSquare, Shield, Award, Zap, Target, TrendingUp, FileCode, Brain, Lock } from 'lucide-react';

const features = [
  { icon: Bot, title: 'AI HS Code Classifier', desc: 'Instantly classify your products with the correct Harmonized System code. 95%+ accuracy powered by Llama 3 AI. Get regulation notes and compliance alerts.', category: 'AI Intelligence' },
  { icon: Globe, title: 'Buyer Radar', desc: 'Access a curated database of global buyers with verified import data from UN Comtrade and customs records. Filter by country, product category, and quality score.', category: 'Premium' },
  { icon: Target, title: 'AI Lead Scoring', desc: 'Our AI analyzes buyer import history, volume trends, and category match to predict conversion probability with a 0-100 Buy Score.', category: 'Premium' },
  { icon: MessageSquare, title: 'Smart Chat & WhatsApp Bridge', desc: 'Communicate with buyers through in-app chat that bridges to WhatsApp. Never miss an inquiry across channels.', category: 'Communication' },
  { icon: Brain, title: 'AI Response Suggestions', desc: 'Get culturally-aware, professional response templates generated by AI. Tailored to each buyer\'s language and market.', category: 'AI Intelligence' },
  { icon: BarChart3, title: 'Inquiry Analytics', desc: 'Track your response rate, conversion rate, repeat buyers, and average response time with beautiful dashboards.', category: 'Analytics' },
  { icon: Award, title: 'Leaderboard System', desc: 'Benchmark your performance against competitors. Transparent scoring across conversion, response rate, and fulfillment.', category: 'Analytics' },
  { icon: FileCode, title: 'AI Listing Optimizer', desc: 'Analyze and optimize your product listings for maximum visibility. Get suggestions for titles, descriptions, keywords, and pricing.', category: 'AI Intelligence' },
  { icon: TrendingUp, title: 'Market Opportunity Alerts', desc: 'Receive real-time notifications when buyers in your target markets are actively looking for your product categories.', category: 'Premium' },
  { icon: Shield, title: 'Document Vault', desc: 'Securely store and share trade documents with AES-256 encryption. PDPA-aligned with granular access controls.', category: 'Security' },
  { icon: Lock, title: 'Enterprise Security', desc: 'JWT authentication, Row-Level Security, 2FA support, and rate limiting to protect your data and transactions.', category: 'Security' },
  { icon: Zap, title: 'Real-time Notifications', desc: 'Multi-channel notifications via email, WhatsApp, and in-app alerts. Never miss an opportunity.', category: 'Communication' },
];

export default function FeaturesPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />

      <section className="relative overflow-hidden py-20">
        <div className="absolute inset-0 bg-gradient-to-br from-primary-50 to-accent-50" />
        <div className="relative container mx-auto px-6 text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Powerful <span className="gradient-text">Features</span>
          </h1>
          <p className="text-lg text-gray-500 max-w-2xl mx-auto">
            Everything you need to discover, qualify, and connect with global buyers — powered by AI intelligence.
          </p>
        </div>
      </section>

      <section className="container mx-auto px-6 py-16">
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
          {features.map((feature, i) => (
            <div key={i} className="card-hover group">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-gradient-to-br from-primary-100 to-accent-100 rounded-xl flex items-center justify-center flex-shrink-0 group-hover:from-primary-200 group-hover:to-accent-200 transition-all">
                  <feature.icon className="w-6 h-6 text-primary-700" />
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="font-semibold text-gray-900">{feature.title}</h3>
                    {feature.category === 'Premium' && (
                      <span className="badge bg-amber-100 text-amber-700 text-[10px]">Premium</span>
                    )}
                  </div>
                  <p className="text-sm text-gray-500 leading-relaxed">{feature.desc}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <Footer />
    </div>
  );
}
