import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Legacy support
        primary: {
          DEFAULT: '#5300b7',
          50: '#F5F3FF', 100: '#EDE9FE', 200: '#DDD6FE', 300: '#C4B5FD',
          400: '#A78BFA', 500: '#8B5CF6', 600: '#7C3AED', 700: '#6D28D9',
          800: '#5B21B6', 900: '#4C1D95',
        },
        accent: {
          DEFAULT: '#3B82F6',
          50: '#EFF6FF', 100: '#DBEAFE', 200: '#BFDBFE', 300: '#93C5FD',
          400: '#60A5FA', 500: '#3B82F6', 600: '#2563EB', 700: '#1D4ED8',
          800: '#1E40AF', 900: '#1E3A8A',
        },
        // M3 Light tokens
        'surface-tint': '#7331df',
        'surface-container-low': '#f9f1ff',
        'error': '#ba1a1a',
        'on-background': '#1d1a24',
        'surface': '#fef7ff',
        'surface-variant': '#e8e0ee',
        'primary-container': '#6d28d9',
        'on-error': '#ffffff',
        'on-primary-fixed': '#250059',
        'inverse-surface': '#332f39',
        'surface-bright': '#fef7ff',
        'primary-fixed-dim': '#d3bbff',
        'on-primary-container': '#dac5ff',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#d3bbff',
        'on-tertiary-container': '#ffc19e',
        'on-secondary-container': '#fefcff',
        'tertiary': '#6b3000',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb68b',
        'surface-container': '#f3ebf9',
        'secondary-container': '#2170e4',
        'surface-container-highest': '#e8e0ee',
        'on-surface': '#1d1a24',
        'on-secondary': '#ffffff',
        'tertiary-container': '#8f4200',
        'background': '#fef7ff',
        'outline-variant': '#ccc3d7',
        'on-primary-fixed-variant': '#5b00c5',
        'surface-container-high': '#ede5f3',
        'on-surface-variant': '#4a4455',
        'secondary': '#0058be',
        'primary-fixed': '#ebddff',
        'on-primary': '#ffffff',
        'surface-dim': '#dfd7e5',
        'on-error-container': '#93000a',
        'outline': '#7b7486',
        'secondary-fixed': '#d8e2ff',
        'inverse-on-surface': '#f6eefc',
        // Dark mode specific
        'dark-surface': '#141218',
        'dark-surface-container': '#211f26',
        'dark-surface-container-low': '#1d1b20',
        'dark-surface-container-high': '#2b2930',
        'dark-surface-container-highest': '#36343b',
        'dark-surface-container-lowest': '#0f0d13',
        'dark-surface-variant': '#49454f',
        'dark-on-surface': '#e6e0e9',
        'dark-on-surface-variant': '#cac4d0',
        'dark-outline': '#938f99',
        'dark-outline-variant': '#49454f',
        'dark-on-background': '#e6e0e9',
        'dark-background': '#141218',
        'dark-primary': '#d0bcff',
        'dark-on-primary': '#381e72',
        'dark-primary-container': '#4f378b',
        'dark-secondary': '#ccc2dc',
        'dark-surface-bright': '#3b383e',
      },
      fontFamily: {
        sans: ['Montserrat', 'sans-serif'],
        headline: ['Montserrat', 'sans-serif'],
        display: ['Montserrat', 'sans-serif'],
        body: ['Montserrat', 'sans-serif'],
        label: ['Montserrat', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 4px 20px rgba(109, 40, 217, 0.08)',
        'ambient-hover': '0 8px 30px rgba(109, 40, 217, 0.12)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
export default config
